version: '3.8'
services:
  database:
    image: mongo
    container_name: mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  backend:
    image: backend-image
    container_name: backend_container
    ports:
      - 3456:3456
    depends_on:
      - database
    environment:
      MONGO_URI: mongodb://root:example@database:27017/nest
  frontend:
    image: frontend-image
    container_name: frontend_container
    ports:
      - 6543:6543
    depends_on:
      - backend
